#ifndef _CONFIG_H_
#define _CONFIG_H_

	#cmakedefine PROJECT_NAME "${CMAKE_PROJECT_NAME}"
	#cmakedefine PROJECT_VERSION "@PROJECT_VERSION@"
	#cmakedefine PROJECT_VERSION_FULL "@PROJECT_VERSION_FULL@"
	#define PROJECT_FULLNAME PROJECT_NAME" "PROJECT_VERSION_FULL

#endif
